from __future__ import annotations

from src.core.component import Component
from src.core.adaptive_context import AdaptiveContext
from src.planning.decision_types import RetrievalStrategy


class AdaptiveRetriever(Component):
    """
    Executes the retrieval plan generated by the
    Decision Engine.
    """

    def __init__(
        self,
        dense_retriever,
        bm25_retriever=None,
        hybrid_retriever=None,
    ):

        self.dense = dense_retriever
        self.bm25 = bm25_retriever
        self.hybrid = hybrid_retriever

    def run(
        self,
        context: AdaptiveContext,
    ) -> AdaptiveContext:

        plan = context.retrieval_plan

        query = context.query

        if plan.strategy == RetrievalStrategy.DENSE:

            documents = self.dense.retrieve(

                query=query,

                top_k=plan.top_k

            )

        elif plan.strategy == RetrievalStrategy.BM25:

            if self.bm25 is None:

                raise RuntimeError(
                    "BM25 Retriever not registered."
                )

            documents = self.bm25.retrieve(

                query=query,

                top_k=plan.top_k

            )

        elif plan.strategy == RetrievalStrategy.HYBRID:

            if self.hybrid is None:

                raise RuntimeError(
                    "Hybrid Retriever not registered."
                )

            documents = self.hybrid.retrieve(

                query=query,

                top_k=plan.top_k

            )

        else:

            raise ValueError(
                f"Unknown retrieval strategy: {plan.strategy}"
            )

        context.retrieved_documents = documents

        context.add_event("retrieval_completed")

        return context